# Generated by Django 3.1.5 on 2021-01-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210109_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.CharField(max_length=200),
        ),
    ]
