# Generated by Django 3.1.5 on 2021-01-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20210109_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
